name: Build and Push 

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repository
    runs-on: ubuntu-latest

    steps:
      # - name: Set variables
      #   id: set-variables
      #   run: |
      #     DOCKER_IMAGE=hywook4/hello-world-go
      #     TAG=$(date -u +'%Y%m%d%H%M%S')

      #     echo ::set-output name=docker_image_tag::${DOCKER_IMAGE}:${TAG}

      # - name: Checkout code
      #   uses: actions/checkout@v3

      # - name: Set up Docker Buildx
      #   id: buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Login to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      # - name: Build image and push to DockerHub
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     platforms: linux/amd64
      #     push: true
      #     tags: ${{ steps.set-variables.outputs.docker_image_tag }}

      - name: Checkout push target repo
        uses: actions/checkout@v3
        with:
          repository: hywook4/argocd-test-application
          ssh-key: ${{ secrets.GIT_HUB_SSH_KEY }}

      - name: Update deployment yaml's image tag
        uses: mikefarah/yq@master
        with:
          cmd: yq '.spec.template.spec.containers[0].image = "${{ steps.set-variables.outputs.docker_image_tag }}"' -i test/application.yaml
        
      - name: Push to target repo
        run: | 
          git config user.name tttt
          git config user.email tttt@gmail.com
          git add .
          git commit -m "update image to latest"
          git push

      # - name: Push change to deployment repository
      #   uses: cpina/github-action-push-to-another-repository@main
      #   env:
      #     SSH_DEPLOY_KEY: ${{ secrets.GIT_HUB_SSH_KEY }}
      #   with:
      #     destination-github-username: hywook4
      #     destination-repository-name: argocd-test-application
      #     target-branch: main