# Build, push image and update deployment spec
name: Build, push and update deployment spec

on:
  # 특정 branch에 push 시 실행
  push:
    branches: [ "main", "develop" ]

jobs:
  test-ci:
    name: Build, push Docker image and update deployment spec
    runs-on: ubuntu-latest

    steps:
      # 환경에 맞춰서 필요한 변수 설정 (TODO: CD 준비되면 수정 DEPLOYMENT_FILE_PATH, DEPLOYMENT_REPO 수정)
      - name: Set variables
        id: set-variables
        run: |
          case ${GITHUB_REF##*/} in
            'main') 
              DOCKER_IMAGE=hywook4/hello-world-go-prod
              DEPLOYMENT_FILE_PATH=prod/application.yaml
              ;;

            'develop') 
              DOCKER_IMAGE=hywook4/hello-world-go-stage
              DEPLOYMENT_FILE_PATH=test/application.yaml
              ;;
          esac

          TAG=$(date -u +'%Y%m%d%H%M%S')

          DEPLOYMENT_REPO=hywook4/argocd-test-application

          echo Will push image to ${DOCKER_IMAGE}:${TAG} 
          echo Will update deployment of ${DEPLOYMENT_REPO}/${DEPLOYMENT_FILE_PATH}

          echo ::set-output name=docker_image_tag::${DOCKER_IMAGE}:${TAG}
          echo ::set-output name=deployment_repo::${DEPLOYMENT_REPO}
          echo ::set-output name=deployment_file_path::${DEPLOYMENT_FILE_PATH}

      # 현재 repo로 checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # Docker buildx 설정
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      # Docker 로그인
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Docker 이미지 빌드, Dockerhub에 이미지 푸시
      - name: Build image and push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.set-variables.outputs.docker_image_tag }}

      # Deployment repo로 checkout
      - name: Checkout to deployment repo
        uses: actions/checkout@v3
        with:
          repository: ${{ steps.set-variables.outputs.deployment_repo }}
          ssh-key: ${{ secrets.GIT_HUB_SSH_KEY }}

      # Deployment spec 수정
      - name: Update deployment yaml's image tag
        uses: mikefarah/yq@master
        with:
          cmd: yq '.spec.template.spec.containers[0].image = "${{ steps.set-variables.outputs.docker_image_tag }}"' -i ${{ steps.set-variables.outputs.deployment_file_path }}
      
      # Deployment 수정사항 deployment repo로 push
      - name: Push deployment update to repo
        run: | 
          git config user.name whitecubeinc
          git config user.email whitecube.xyz@gmail.com
          git add .
          git commit -m "update deployment spec image to ${{ steps.set-variables.outputs.docker_image_tag }}"
          git push

